[package]
name = "bevy-clipmap"
version = "0.17.3"
edition = "2024"
license = "MIT"
description = "Render huge 3D worlds using Bevy!"

[dependencies]
bevy = { version = "0.17.3", features = ["basis-universal"] }
bevy-inspector-egui = "0.35"
bevy_flycam = "0.17.0"
